### ISSUE TITLE
delete player - no warning

### ISSUE THREAD

**Issue by helenvarley** [AUTUpStageTeam/UpStage#200]
the trash icon next to the save icon in the edit player screen deletes the player, without warning. it would be good to have a similar pop-up window as there is for deleting avatars, that allows you to cancel (sometimes people's fingers slip! or they might think, because it's next to the save button, that they are only cancelling changes to that player, not deleting them).

**Comment by project-yue** [comment]
Tested the function from V3.3.
When admin edits user accounts, delete user function stopped working.
When user with admin previlege clicks on Delete User Option, no action was done.

Will look into the version history.

**Comment by helenvarley** [comment]
great - does this mean it's now working properly?

**Comment by project-yue** [comment]
Yes, now it deletes with warning.

**Comment by yue-l** [comment]
This issue is closed.

All the previous details should be sufficient as description.
