### ISSUE TITLE
Player Access Controls from Stage Edit Page

### ISSUE THREAD

**Issue by VanessaHenderson** [AUTUpStageTeam/UpStage#234]
Acceptance Testing revealed that if try and move a player down an access level, players that you had not selected to move may also move player access levels. 
This happened in all browsers.
Didn't happen with moving players up an access level

**Comment by yue-l** [comment]
Completed test actions today on AUT server 8081 & public server 8083 in Version 3.4.

- Preparations Done (on Profile Edit page):
  * added multiple users with different privileges.

- Actions Done (on Stage Edit page):
  * Scenario 1 moved up users access level from audience to player, then move 1 user access level down to audience. No other users affected.
  * Scenario 2 moved up users access level from audience to player and player to admin, then move 1 user access level down to audience. No other users affected.
  * Scenario 3 moved up users access level from audience to player, Save Stage, then move 1 user access level down to audience. No other users affected.
  * Scenario 4 moved up users access level from audience to player and player to admin, Save Stage, then move 1 user access level down to audience. No other users affected.

Tested under Chrome 41.0, Mozila Firefox 35.0.

Await for further reports from other team members.

**Comment by lottle** [comment]
Completed a test today on server 8081.

•	Preparation: Added multiple users with different privileges.
•	Action: 
            Tested each of the scenarios in the previous comment and found no sign of the issue. 
            Found that only selected users moved between the access panels.
Tested on Chrome 41.0 and Firefox 37.01

**Comment by yue-l** [comment]
I think this issue occurred because of errors in the web page (could be missing closing brace caused the error).

Currently the same issue no longer makes appearances in v3.4.2
