### ISSUE TITLE
"too many open files" bug

### ISSUE THREAD

**Issue by helenvarley** [AUTUpStageTeam/UpStage#256]
today we had a situation where none of us (5 people) could enter http://upstage.org.nz:8083/ - we were all getting the error message "too many open files" (see attached image). this has happened in the past but usually to only one person at a time, & reloading solves it. this time it happened to all of us who were trying to enter, & not only the stages but everything past the home page, & it continued for some time. mem reported it last night, i checked & was able to enter, but this morning could not & nobody could.

paul has restarted the instance as a temporary fix, but said to log it as a high priority bug, saying "This happens when connections aren't closed properly. It's a combination of a Linux security feature and poor connection handling in UpStage code. I CAN increase the limit at the OS level, but the BEST solution is to fix the code - think of it as a memory leak of sorts."

![toomanyopenfiles](https://cloud.githubusercontent.com/assets/3437324/4907547/79811e8a-6462-11e4-9d85-451f03061a44.jpg)

**Comment by yue-l** [comment]
This happens when issues occur during server deployment processes.
Currently UpStage server does not suffer this situation.
