### ISSUE TITLE
clickable links in chat

### ISSUE THREAD

**Issue by helenvarley** [AUTUpStageTeam/UpStage#258]
it would be great if links in the chat text were clickable. at the moment, you have to right-click on the link then choose "open link in new tab". what would be nice is if you could just click on the link, & it automatically opens in a new tab.

**Comment by project-yue** [comment]
Tasks done:
Checked onMouseDown() method in ModelChat class,
Function event has no effect on application.

**Comment by helenvarley** [comment]
yue reported today that to achieve this will require rewriting the whole class, as the chat box is currently a single object and would need to be rewritten as a container. we decided that this is a low priority for v3, instead we should develop this within the new UpStage.

**Comment by helenvarley** [comment]
actually the links don't work at all now, even when right-clicked. when you paste in a link it adds an extra http:// and then when you right click on it, it leaves the : out of the url.

**Comment by wbv5134** [comment]
Tried to find the onMouseDown() method in ModelChat as Yue has mentioned earlier but cannot find it.

Testing on a stage (in :8081) shows that when typing url with "http://" the http:// is not repeated unless the url starts with "https://" which then looks like http://https://github.com/.... 

When opening the link http://https://github.com/..., it becomes https//github.com/... just as helen said, it leaves out the : of the url.

**Comment by yue-l** [comment]
Thanks. I meant ChatField class.

I think this ticket should only focus on text-clicking events. Should create another ticket for the wrong link output. Refer to issue #267, line 300 - 350 in ChatField class.

**Comment by rohrlach** [comment]
Slight nitpick: the code to actually follow the link should be onMouseUp

**Comment by yue-l** [comment]
This issue refers to #267 for more detailed information. 

The clicking feature described in this issue is beyond the scope of v3. 
Recorded this issue as new requirement for the new UpStage implementation.
