### ISSUE TITLE
Animation fails to play

### ISSUE THREAD

**Issue by yue-l** [AUTUpStageTeam/UpStage#268]
As taken actions fixing errors in the server deployment processes. swftools seems failing as none animation works for any uploaded gif or swf file..

This problem has been discovered from v3.0-beta and later releases..
This is a part of compilation issue alongside mtasc compilation.

**Comment by yue-l** [comment]
As in the first place, team thought it could be the issue for the later releases.
I want to eliminate investigation areas, so I think if different versions of Firefox browsers produce different results, this could be a sign of impact from NPAPI deprecation. 
Action taken:
- Installed Firefox 28 on Windows 7 Pro. Consider release version suitable.
- Deployed 3.4.1 on AUT server 8081
- regular compilation process from server installation manual followed

Result from img2swf.log

>2015-05-26 01:15:18
arguments are:
html/media/oYKwLAsQ.swf
html/media/thumb/oYKwLAsQ.jpg
/tmp/tmpEEWXQm
Files are: ['/tmp/tmpEEWXQm']
filetype: image/gif
Filetype is 'image/gif', convertor is <function do_gif at 0xb72449cc>
Done SWF, got 0, gif2swf -o html/media/oYKwLAsQ.swf /tmp/tmpEEWXQm
no errors yet!
giftopnm /tmp/tmpEEWXQm | pnmscale -height=80 -width=70 | pnmtojpeg > /tmp/tmpb1SQl4.jpg
removing /tmp/tmpEEWXQm
>worked, or at least failed to complain.

Will further look into swftools compilation

**Comment by yue-l** [comment]
Traced img2swf log details:

- media swf and jpg are generated correctly. 
- the swf file is assigned to the test stage correctly.

**Comment by yue-l** [comment]
Tested all released versions from v2.4.4 onwards

- Tried earlier Firefox version 28 with Flash 11, v2.4.4 fails to upload swf file onto the server from media upload page.
- Tried Firefox 28 with Flash 11, 3.4.2, the latest version will upload swf file. However, the frames embedded in swf still dont load at all.

**Comment by helenvarley** [comment]
note: i think that gif animations have never worked. if you upload an animated gif i think it only ever showed a still image (unless you upload multiple frames).

**Comment by yue-l** [comment]
After few tests, I might have found the cause. It may be something with the image resolution.
The current implementation should convert all uploaded media into swf form.

**Comment by helenvarley** [comment]
from the beginning UpStage has converted all uploaded media to swf form. there was a change in the resolution somewhere between v 2.1 & v3. up to v2.1 we always had to make avatars approximately 1/3 smaller than we wanted them to appear, as they "grew" during the upload process. this was because of the changing resolution of computer screens according to what UpStage was originally built for. then, at something like v2.4, it became that avatars would remain pretty much at their original size after upload. (this is one of the reasons why we kept upstage.org.nz:8084 at v2.1, because all of the media on that instance is the old size, & if uploaded to newer versions of UpStage it appears very very small).

this may have nothing to do with the current problem, but it is some of the back-story so maybe will fill in some gaps or explain something :)

**Comment by yue-l** [comment]
I ran a different set of tests today:
Action:
- Loaded both gif and swf format onto the stage.

Results:
- gif fails to play animation at all
- swf fails to play on the stage
- swf animation runs well on wardrobe

Thanks @helenvarley for pointing my tests out. At the time, I converted gif to swf explicitly. Hmmm, it is questionable on UpStage dependency gif2swf.
Should identify if gif2swf dependency still functional??

**Comment by yue-l** [comment]
After today's client meeting, we found we may have achieved something UpStage has been claiming lack of.

- Avatars animation must be triggered by special command "/a number". This explains why avatar in swf format plays well in wardrobe.
- Avatar uploaded in gif extension also animates well.

gif extension avatar does not animate in wardrobe, so this may be a different issue.

great to see things working in order. I will close this issue.

**Comment by helenvarley** [comment]
yay, great to have .swfs animating again, AND the bonus of animated gifs working as well! :) i will update the user manual.

**Comment by helenvarley** [comment]
quick question as i update the user manual: do you know if animated gifs will work as backdrops? & have you checked .swf backdrops? (i can do this later, just wondering if the student team has already tried it).

**Comment by yue-l** [comment]
Hi @helenvarley, media in swf format should be able to play without any issue. 

- .swf backdrops play without problem.
- .gif backdrops don't play. so this still an issue team can look into in the future.

As .gif file works with command '/a 0', I think this could be a lead for us..

**Comment by helenvarley** [comment]
@yue-l do you sleep??? ;)

**Comment by yue-l** [comment]
hmmm, I really wanted to though.
But I have to complete all my other commitments too. (I don't want to fail any of my papers)

**Comment by helenvarley** [comment]
we give you an A+ with 2 gold stars!

**Comment by vickis** [comment]
Yue you and the team have done an awesome job - I am sure you are doing as well in your other papers! 
we shower you with gold stars and good grades!!

- Ps it was great to find the gif animation working and i am sorry i didn't click earlier that you weren't using /a 0 , /a 1 etc to manipulate on stage

the  animation for backdrop is triggered by /b 

note to the architects Helen (to keep the code bg fresh in everyone's minds for testing ;)

kia pai to ra
vicki ("

**Comment by yue-l** [comment]
@vickis @helenvarley ahhhh, tested gif file as backdrop and prob... it works!!!!
Thanks a lot for the extra information :)

**Comment by yue-l** [comment]
I think the problem was gif2swf package was not included as part of UpStage dependencies... I could only see gif2png in the existing dependency list.

**Comment by vickis** [comment]
super star!

kia pai to ra
vicki ("

**Comment by helenvarley** [comment]
woohoo!!! :)

**Comment by yue-l** [comment]
an update about gif2swf package info: 

I checked gif2swf package on Debian Wheezy Repository. gif2swf package acts as a sub-package of swftools. Also checked the related bugs on gif2swf, all the major issues were fixed in the later 2013.
